### PR TITLE
Update rebasing instructions

### PR DESCRIPTION
**Pull request by kpedro88**
NB: this PR relies on https://github.com/cms-sw/cms-git-tools/pull/79.

I wrote a new tutorial for rebasing PRs, using my new tool `cms-checkout-topic`. This is intended to avoid the frequent (almost daily) problem of people following the old tutorial, which was objectively incorrect, and performing merges that add 100s of commits into their branches.

I also cleaned up a few minor things in the webpages.

Question: is the "How can I prevent automatic forward porting of a pull request?" section in the FAQ still correct? I didn't think this was done anymore. If it is no longer correct, please let me know and I will update the PR to remove it.

### CODE REVIEW

**Comment by smuzaffar** [comment]
Thanks @kpedro88  for this.
Yes then question "How can I prevent automatic forward porting of a pull request?"  is not needed any more.

**Comment by kpedro88** [comment]
@smuzaffar can you explain to me how this repo is maintained that causes spontaneous merge conflicts once a week? It is rather frustrating to keep remaking the same PR. Please let me know when you are ready to merge my changes to the public webpages, and then I will resolve the conflicts.

**Comment by smuzaffar** [comment]
@kpedro88 , in this repo cms-bot and various jenkins jobs dumps  IBs related information (which is then served via github.io)  e.g.
- IBs build stats (build errors, relval, addon test etc)
- cache das queries etc
basically every 5 to 10 mins there is a commit and over the time this repository got too big that we were asked to clean it. Also because of it size it was taking too much time to clone and push new data.

So now every week we cleanup the history of this repository. History is only cleaned up for the data generated for IBs and das queries.

Do not worry about the conflicts , I will resolve them next week when I will review these changes ( I am away this week)

**Comment by kpedro88** [comment]
Even with that procedure of cleaning up history, the repo is still rather slow when I clone it locally. Maybe we should consider separating the public webpage content from the build stats and DAS queries, to make it easier to keep the FAQs/tutorials up to date?

**Comment by smuzaffar** [comment]
humm how slow is it? For me it is reasonable (order of 10s)
```
time git clone git@github.com:cms-sw/cms-sw.github.io.git
Cloning into 'cms-sw.github.io'...
remote: Counting objects: 41945, done.
remote: Compressing objects: 100% (1326/1326), done.
remote: Total 41945 (delta 1007), reused 0 (delta 0), pack-reused 40528
Receiving objects: 100% (41945/41945), 33.09 MiB | 14.03 MiB/s, done.
Resolving deltas: 100% (30327/30327), done.
Checking out files: 100% (21728/21728), done.
5.872u 2.072s 0:10.50 75.6%     0+0k 0+703664io 0pf+0w
```

**Comment by kpedro88** [comment]
I found that some git operations (after I had cloned the repo) could take quite a while, e.g.:
```
time git diff
0.063u 3.092s 4:10.62 1.2%      0+0k 0+0io 0pf+0w
```

**Comment by smuzaffar** [comment]
this is done via https://github.com/cms-sw/cms-sw.github.io/commit/0dbc2204e596725b2f88f7316235c0f555c9c8da

**Comment by kpedro88** [comment]
@smuzaffar when will the new tool be available in standard IBs? Right now it is a bit confusing to have the documentation reference a tool that is not accessible.

**Comment by smuzaffar** [comment]
ah right, I will revet the changes then as it will take some time to get the changes tested

**Comment by kpedro88** [comment]
what is the procedure for testing and approving a new git tool? `cms-checkout-topic` was merged a while ago, which you said puts it into the DEVEL builds. I would prefer for it to be available for users sooner rather than later, because it addresses an ongoing difficulty with rebasing PRs.

**Comment by smuzaffar** [comment]
I have run few thing locally to make sure things works. Putting it in any IB can break all IBs (as it is a shared package b.w all archs and IB)

**Comment by kpedro88** [comment]
As an additional data point, I've been using the `cms-checkout-topic` tool myself regularly for the past few weeks (just by sourcing the `init` script in my local clone of `cms-git-tools`) and haven't encountered any problems.

**Comment by smuzaffar** [comment]
@kpedro88 , every thing looks good except some issues with git-cms-rmpkg. 
  - rmpkg can be used to delete a package which was part of a cms-merge-topic. In this case things can fail.
  - when we delete a package (after it has been built once) then it leaves the newly generated files e.g. package/python/*.pyc files in the area. This can also cause problems.
  - SCRAM/build rules also needs update to support rmpkg as it still create lib/$SCRAM_ARCH/.poisonededmplugincache file for the deleted plugins.

I would suggest to drop rmpkg.

**Comment by kpedro88** [comment]
@smuzaffar it's fine with me to drop rmpkg for now if it's causing difficulties. I still have my branch, so I can try to address those issues at a later time.

**Pull request closed without merging**
