### PR TITLE
Added a plot for visualizing all states of PRs

### PR DESCRIPTION
**Pull request by andrius-k**
Added a plot that shows all 3 states of Pull Requests (Approved, Pending and Rejected). It is accessible here `http://cms-sw.github.io/stats/pr-states.html`

### CODE REVIEW

**Comment by andrius-k** [comment]
Hi,

Is there any problem with this PR? Otherwise, would it be possible to merge it?

**Comment by gudrutis** [comment]
We were not expecting for new improvements in this repo - we used it mostly to dump JSON files for fronted.

Anyway, this PR is in mess now - 250+ commits and it has a merge conflict. Could you clean it up? I dont know how you managed to make cmsbuild to push to your fork...

**Comment by andrius-k** [comment]
Hi,

Bot didn't commit to my branch. Apparently bot removed commits from the master after I submitted this PR and therefore my PR contains all of them right now. I will try to fix this.

In general I just added one more page that uses the same JSON files as data to show more detailed statistics about PR reviewals which is important for us.

**Comment by andrius-k** [comment]
Ok, using the magic of git I was able to fix this issue and now the PR is clean. If it is common for bot to remove commits maybe we should merge this as soon as possible.

**Comment by gudrutis** [comment]
I see, I never saw this kind of issue before. Probably this is one of our optimizations to keep repo size minimum. Anyway, I merged your PR and your changes are already visible. Enjoy.

**Comment by davidlange6** [comment]
This happens for any pr for this repo.. we've mixed human generated code/documentation with some automatic processing in one repo. Likely something to consider separating at some point.

**Comment by gudrutis** [comment]
Maybe it is not best to piggy-back on old PR, but I just wanted to let you know that I created I separate [branch](https://github.com/cms-sw/cms-sw.github.io/tree/code) just for this repo's code. I suggest to 
make all new commits/PR's bassed on that branch and then merge it to master.

**Pull request merged**
